export const isProduction = Bun.env.NODE_ENV === 'production'

export const NATS_HOST = Bun.env.NATS_HOST
export const NATS_TOKEN = Bun.env.NATS_AUTH_TOKEN;

export const REDIS_HOST = Bun.env.REDIS_HOST

export const LGOGER_BOT_TOKEN = Bun.env.BOT_TOKEN

export const SQLITE_DATABASE_URL = Bun.env.SQLITE_DATABASE_URL;

export const SKINS_MYSQL_HOST = Bun.env.SKINS_MYSQL_HOST
export const SKINS_MYSQL_PORT = Bun.env.SKINS_MYSQL_PORT
export const SKINS_MYSQL_USER = Bun.env.MYSQL_USER
export const SKINS_MYSQL_PASSWORD = Bun.env.MYSQL_ROOT_PASSWORD
export const SKINS_MYSQL_DB = Bun.env.SKINS_MYSQL_DB

export const REPUTATION_MYSQL_HOST = Bun.env.REPUTATION_MYSQL_HOST
export const REPUTATION_MYSQL_PORT = Bun.env.REPUTATION_MYSQL_PORT
export const REPUTATION_MYSQL_USER = Bun.env.MYSQL_USER
export const REPUTATION_MYSQL_PASSWORD = Bun.env.MYSQL_ROOT_PASSWORD
export const REPUTATION_MYSQL_DB = Bun.env.REPUTATION_MYSQL_DB

export const PLAYERPOINTS_MYSQL_HOST = Bun.env.PLAYERPOINTS_MYSQL_HOST
export const PLAYERPOINTS_MYSQL_PORT = Bun.env.PLAYERPOINTS_MYSQL_PORT
export const PLAYERPOINTS_MYSQL_USER = Bun.env.MYSQL_USER
export const PLAYERPOINTS_MYSQL_PASSWORD = Bun.env.MYSQL_ROOT_PASSWORD
export const PLAYERPOINTS_MYSQL_DB = Bun.env.PLAYERPOINTS_MYSQL_DB

export const GENERAL_POSTGRES_HOST = Bun.env.GENERAL_POSTGRES_HOST
export const GENERAL_POSTGRES_PORT = Bun.env.GENERAL_POSTGRES_PORT
export const GENERAL_POSTGRES_USER = Bun.env.GENERAL_POSTGRES_USER
export const GENERAL_POSTGRES_PASSWORD = Bun.env.GENERAL_POSTGRES_PASSWORD
export const GENERAL_POSTGRES_DB = Bun.env.GENERAL_POSTGRES_DB

export const PAYMENTS_POSTGRES_HOST = GENERAL_POSTGRES_HOST
export const PAYMENTS_POSTGRES_PORT = GENERAL_POSTGRES_PORT
export const PAYMENTS_POSTGRES_USER = GENERAL_POSTGRES_USER
export const PAYMENTS_POSTGRES_PASSWORD = GENERAL_POSTGRES_PASSWORD
export const PAYMENTS_POSTGRES_DB = Bun.env.PAYMENTS_POSTGRES_DB

export const LUCKPERMS_POSTGRES_HOST = Bun.env.LUCKPERMS_POSTGRES_HOST
export const LUCKPERMS_POSTGRES_DB = Bun.env.LUCKPERMS_POSTGRES_DB
export const LUCKPERMS_POSTGRES_PORT = Bun.env.LUCKPERMS_POSTGRES_PORT
export const LUCKPERMS_POSTGRES_USER = Bun.env.LUCKPERMS_POSTGRES_USER
export const LUCKPERMS_POSTGRES_PASSWORD = Bun.env.LUCKPERMS_POSTGRES_PASSWORD

export const LOBBY_MYSQL_HOST = Bun.env.LOBBY_MYSQL_HOST
export const LOBBY_MYSQL_PORT = Bun.env.LOBBY_MYSQL_PORT
export const LOBBY_MYSQL_USER = Bun.env.MYSQL_USER
export const LOBBY_MYSQL_PASSWORD = Bun.env.MYSQL_ROOT_PASSWORD
export const LOBBY_MYSQL_DB = Bun.env.LOBBY_MYSQL_DB

export const BISQUITE_MYSQL_HOST = Bun.env.BISQUITE_MYSQL_HOST
export const BISQUITE_MYSQL_PORT = Bun.env.BISQUITE_MYSQL_PORT
export const BISQUITE_MYSQL_USER = Bun.env.MYSQL_USER
export const BISQUITE_MYSQL_PASSWORD = Bun.env.MYSQL_ROOT_PASSWORD
export const BISQUITE_MYSQL_DB = Bun.env.BISQUITE_MYSQL_DB

export const FRONTEND_ENDPOINT = Bun.env.FRONTEND_ENDPOINT
export const VOLUME_ENDPOINT = Bun.env.VOLUME_ENDPOINT
export const DOMAIN_NAME = Bun.env.DOMAIN_NAME

export const MINIO_ENDPOINT = Bun.env.MINIO_ENDPOINT
export const MINIO_ACCESS_KEY = Bun.env.MINIO_ACCESS_KEY
export const MINIO_SECRET_KEY = Bun.env.MINIO_SECRET_KEY
export const MINIO_PORT = 9000

export const REDIS_PORT = Bun.env.REDIS_PORT
export const REDIS_PASSWORD = Bun.env.REDIS_USER_PASSWORD
export const REDIS_USER = Bun.env.REDIS_USER

export const CRYPTO_PAY_TESTNET_TOKEN = Bun.env.CRYPTO_PAY_TESTNET_TOKEN