/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AUTH {
  HASH: string;
  IP: string | null;
  ISSUEDTIME: Int8 | null;
  LOGINDATE: Int8 | null;
  LOGINIP: string | null;
  LOWERCASENICKNAME: string;
  NICKNAME: string;
  PREMIUMUUID: string | null;
  REGDATE: Int8 | null;
  TOTPTOKEN: string | null;
  UUID: string | null;
}

export interface Events {
  created_at: Generated<Timestamp | null>;
  description: string;
  id: Generated<number>;
  origin: string;
  reward: string | null;
  title: string;
}

export interface EventsOriginal {
  id: Generated<number>;
  type: string;
}

export interface GameStatus {
  id: Generated<number>;
  joined: Timestamp | null;
  nickname: string;
  quited: Timestamp | null;
}

export interface SOCIAL {
  BLOCKED: boolean | null;
  DISCORD_ID: Int8 | null;
  LOWERCASENICKNAME: string;
  NOTIFY_ENABLED: boolean | null;
  TELEGRAM_ID: Int8 | null;
  TOTP_ENABLED: boolean | null;
  VK_ID: Int8 | null;
}

export interface StoreCartItems {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  nickname: string;
  price_snapshot: string;
  product_id: number;
  quantity: number;
  session_id: string | null;
}

export interface StoreEconomy {
  description: string;
  id: Generated<number>;
  imageUrl: string;
  title: string;
  type: string;
  value: string;
}

export interface StoreItems {
  currency: string;
  description: Json | null;
  id: Generated<number>;
  imageUrl: string | null;
  price: Int8;
  summary: string;
  title: string;
  type: string;
  value: string;
}

export interface DB {
  AUTH: AUTH;
  events: Events;
  events_original: EventsOriginal;
  game_status: GameStatus;
  SOCIAL: SOCIAL;
  store_cart_items: StoreCartItems;
  store_economy: StoreEconomy;
  store_items: StoreItems;
}
