/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface LibertybansAddresses {
  address: Buffer;
  updated: Int8;
  uuid: string;
}

export interface LibertybansApplicableActive {
  address: Buffer | null;
  end: Int8 | null;
  id: Int8 | null;
  operator: string | null;
  reason: string | null;
  scope: string | null;
  scope_type: number | null;
  start: Int8 | null;
  track: string | null;
  type: number | null;
  uuid: string | null;
  victim_address: Buffer | null;
  victim_type: number | null;
  victim_uuid: string | null;
}

export interface LibertybansApplicableBans {
  address: Buffer | null;
  end: Int8 | null;
  id: Int8 | null;
  operator: string | null;
  reason: string | null;
  scope: string | null;
  scope_type: number | null;
  start: Int8 | null;
  track: string | null;
  type: number | null;
  uuid: string | null;
  victim_address: Buffer | null;
  victim_type: number | null;
  victim_uuid: string | null;
}

export interface LibertybansApplicableHistory {
  address: Buffer | null;
  end: Int8 | null;
  id: Int8 | null;
  operator: string | null;
  reason: string | null;
  scope: string | null;
  scope_type: number | null;
  start: Int8 | null;
  track: string | null;
  type: number | null;
  uuid: string | null;
  victim_address: Buffer | null;
  victim_type: number | null;
  victim_uuid: string | null;
}

export interface LibertybansApplicableMutes {
  address: Buffer | null;
  end: Int8 | null;
  id: Int8 | null;
  operator: string | null;
  reason: string | null;
  scope: string | null;
  scope_type: number | null;
  start: Int8 | null;
  track: string | null;
  type: number | null;
  uuid: string | null;
  victim_address: Buffer | null;
  victim_type: number | null;
  victim_uuid: string | null;
}

export interface LibertybansApplicableWarns {
  address: Buffer | null;
  end: Int8 | null;
  id: Int8 | null;
  operator: string | null;
  reason: string | null;
  scope: string | null;
  scope_type: number | null;
  start: Int8 | null;
  track: string | null;
  type: number | null;
  uuid: string | null;
  victim_address: Buffer | null;
  victim_type: number | null;
  victim_uuid: string | null;
}

export interface LibertybansBans {
  id: Int8;
  victim: number;
}

export interface LibertybansHistory {
  id: Int8;
  victim: number;
}

export interface LibertybansLatestAddresses {
  address: Buffer | null;
  updated: Int8 | null;
  uuid: string | null;
}

export interface LibertybansLatestNames {
  name: string | null;
  updated: Int8 | null;
  uuid: string | null;
}

export interface LibertybansMessages {
  message: Buffer;
  time: Int8;
}

export interface LibertybansMutes {
  id: Int8;
  victim: number;
}

export interface LibertybansNames {
  lower_name: Generated<string | null>;
  name: string;
  updated: Int8;
  uuid: string;
}

export interface LibertybansPunishments {
  end: Int8;
  id: Int8;
  operator: string;
  reason: string;
  scope: string;
  scope_id: number | null;
  start: Int8;
  track: number | null;
  type: number;
}

export interface LibertybansRevision {
  constant: string;
  major: number;
  minor: number;
}

export interface LibertybansSchemaHistory {
  checksum: number | null;
  description: string;
  execution_time: number;
  installed_by: string;
  installed_on: Generated<Timestamp>;
  installed_rank: number;
  script: string;
  success: boolean;
  type: string;
  version: string | null;
}

export interface LibertybansScopes {
  id: number;
  type: number;
  value: string;
}

export interface LibertybansSimpleActive {
  end: Int8 | null;
  id: Int8 | null;
  operator: string | null;
  reason: string | null;
  scope: string | null;
  scope_type: number | null;
  start: Int8 | null;
  track: string | null;
  type: number | null;
  victim_address: Buffer | null;
  victim_type: number | null;
  victim_uuid: string | null;
}

export interface LibertybansSimpleBans {
  end: Int8 | null;
  id: Int8 | null;
  operator: string | null;
  reason: string | null;
  scope: string | null;
  scope_type: number | null;
  start: Int8 | null;
  track: string | null;
  type: number | null;
  victim_address: Buffer | null;
  victim_type: number | null;
  victim_uuid: string | null;
}

export interface LibertybansSimpleHistory {
  end: Int8 | null;
  id: Int8 | null;
  operator: string | null;
  reason: string | null;
  scope: string | null;
  scope_type: number | null;
  start: Int8 | null;
  track: string | null;
  type: number | null;
  victim_address: Buffer | null;
  victim_type: number | null;
  victim_uuid: string | null;
}

export interface LibertybansSimpleMutes {
  end: Int8 | null;
  id: Int8 | null;
  operator: string | null;
  reason: string | null;
  scope: string | null;
  scope_type: number | null;
  start: Int8 | null;
  track: string | null;
  type: number | null;
  victim_address: Buffer | null;
  victim_type: number | null;
  victim_uuid: string | null;
}

export interface LibertybansSimpleWarns {
  end: Int8 | null;
  id: Int8 | null;
  operator: string | null;
  reason: string | null;
  scope: string | null;
  scope_type: number | null;
  start: Int8 | null;
  track: string | null;
  type: number | null;
  victim_address: Buffer | null;
  victim_type: number | null;
  victim_uuid: string | null;
}

export interface LibertybansStrictLinks {
  uuid1: string | null;
  uuid2: string | null;
}

export interface LibertybansTracks {
  id: number;
  namespace: string;
  value: string;
}

export interface LibertybansVictims {
  address: Buffer;
  id: number;
  type: number;
  uuid: string;
}

export interface LibertybansWarns {
  id: Int8;
  victim: number;
}

export interface DB {
  libertybans_addresses: LibertybansAddresses;
  libertybans_applicable_active: LibertybansApplicableActive;
  libertybans_applicable_bans: LibertybansApplicableBans;
  libertybans_applicable_history: LibertybansApplicableHistory;
  libertybans_applicable_mutes: LibertybansApplicableMutes;
  libertybans_applicable_warns: LibertybansApplicableWarns;
  libertybans_bans: LibertybansBans;
  libertybans_history: LibertybansHistory;
  libertybans_latest_addresses: LibertybansLatestAddresses;
  libertybans_latest_names: LibertybansLatestNames;
  libertybans_messages: LibertybansMessages;
  libertybans_mutes: LibertybansMutes;
  libertybans_names: LibertybansNames;
  libertybans_punishments: LibertybansPunishments;
  libertybans_revision: LibertybansRevision;
  libertybans_schema_history: LibertybansSchemaHistory;
  libertybans_scopes: LibertybansScopes;
  libertybans_simple_active: LibertybansSimpleActive;
  libertybans_simple_bans: LibertybansSimpleBans;
  libertybans_simple_history: LibertybansSimpleHistory;
  libertybans_simple_mutes: LibertybansSimpleMutes;
  libertybans_simple_warns: LibertybansSimpleWarns;
  libertybans_strict_links: LibertybansStrictLinks;
  libertybans_tracks: LibertybansTracks;
  libertybans_victims: LibertybansVictims;
  libertybans_warns: LibertybansWarns;
}
