/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type PaymentStatus = "canceled" | "pending" | "succeeded" | "waitingForCapture";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Payments {
  asset: string;
  comment: string | null;
  created_at: Generated<Timestamp>;
  id: number;
  initiator: string;
  invoice_id: number;
  order_id: string;
  pay_url: string;
  payload: string;
  price: string;
  status: PaymentStatus;
  unique_id: string;
}

export interface PaymentsGame {
  created_at: Generated<Timestamp>;
  finished_at: Timestamp | null;
  id: Generated<number>;
  initiator: string;
  item_id: number;
  unique_id: string;
}

export interface PaymentsGameChilds {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  recipient: string;
  store_item_id: number;
}

export interface DB {
  payments: Payments;
  payments_game: PaymentsGame;
  payments_game_childs: PaymentsGameChilds;
}
