/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface SrCache {
  name: string;
  timestamp: number;
  uuid: Generated<string | null>;
}

export interface SrCooldowns {
  creation_time: number;
  duration: number;
  group_name: string;
  uuid: string;
}

export interface SrCustomSkins {
  display_name: Generated<string | null>;
  name: string;
  signature: string;
  value: string;
}

export interface SrPlayerFavourites {
  skin_identifier: string;
  skin_type: string;
  skin_variant: Generated<string | null>;
  timestamp: number;
  uuid: string;
}

export interface SrPlayerHistory {
  skin_identifier: string;
  skin_type: string;
  skin_variant: Generated<string | null>;
  timestamp: number;
  uuid: string;
}

export interface SrPlayers {
  skin_identifier: Generated<string | null>;
  skin_type: Generated<string | null>;
  skin_variant: Generated<string | null>;
  uuid: string;
}

export interface SrPlayerSkins {
  last_known_name: Generated<string | null>;
  signature: string;
  timestamp: number;
  uuid: string;
  value: string;
}

export interface SrUrlIndex {
  skin_variant: Generated<string | null>;
  url: string;
}

export interface SrUrlSkins {
  mine_skin_id: Generated<string | null>;
  signature: string;
  skin_variant: Generated<string | null>;
  url: string;
  value: string;
}

export interface DB {
  sr_cache: SrCache;
  sr_cooldowns: SrCooldowns;
  sr_custom_skins: SrCustomSkins;
  sr_player_favourites: SrPlayerFavourites;
  sr_player_history: SrPlayerHistory;
  sr_player_skins: SrPlayerSkins;
  sr_players: SrPlayers;
  sr_url_index: SrUrlIndex;
  sr_url_skins: SrUrlSkins;
}
