/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Admins {
  created_at: Generated<string>;
  id: Generated<number | null>;
  nickname: string;
}

export interface Currencies {
  id: Generated<number | null>;
  imageUrl: string;
  isAvailable: Generated<number>;
  isPublic: Generated<number>;
  title: string;
  value: string;
}

export interface Findout {
  findout: string | null;
  id: Generated<number | null>;
  nickname: string;
}

export interface IpList {
  id: Generated<number | null>;
  ip: string;
  name: string;
}

export interface Likes {
  created_at: Generated<string>;
  id: Generated<number | null>;
  initiator: string;
  recipient: string;
}

export interface MinecraftFacts {
  fact: string;
  id: Generated<number | null>;
}

export interface MinecraftItems {
  description: string | null;
  id: Generated<number | null>;
  image: string;
  title: string;
}

export interface MinecraftNews {
  created_at: Generated<string>;
  description: string;
  id: Generated<number>;
  imageUrl: string;
  media_links: string | null;
  tags: string | null;
  title: string;
}

export interface Modpacks {
  client: string;
  created_at: Generated<string>;
  downloadLink: string;
  id: Generated<number | null>;
  imageUrl: string;
  mods: string;
  name: string;
  shaders: string | null;
  version: string;
}

export interface NewsViews {
  id: Generated<number | null>;
  initiator: string;
  news_id: number;
}

export interface Referrals {
  completed: Generated<number>;
  created_at: Generated<string>;
  id: Generated<number | null>;
  initiator: string;
  recipient: string;
}

export interface RulesContent {
  description: string | null;
  id: Generated<number | null>;
  punishment: string | null;
  rule_list_id: string;
  subtitle: string | null;
  title: string;
}

export interface RulesTermins {
  article_desc: string;
  article_title: string;
  id: Generated<number | null>;
}

export interface VotedUsers {
  created_at: Generated<string>;
  id: Generated<number | null>;
  nickname: string;
}

export interface DB {
  admins: Admins;
  currencies: Currencies;
  findout: Findout;
  ip_list: IpList;
  likes: Likes;
  minecraft_facts: MinecraftFacts;
  minecraft_items: MinecraftItems;
  minecraft_news: MinecraftNews;
  modpacks: Modpacks;
  news_views: NewsViews;
  referrals: Referrals;
  rules_content: RulesContent;
  rules_termins: RulesTermins;
  voted_users: VotedUsers;
}
