/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface IpList {
  id: Generated<number | null>;
  ip: string;
  name: string;
}

export interface MinecraftNews {
  created_at: Generated<string>;
  description: string;
  id: Generated<number>;
  imageUrl: string;
  media_links: string | null;
  tags: string | null;
  title: string;
}

export interface Modpacks {
  client: string;
  created_at: Generated<string>;
  downloadLink: string;
  id: Generated<number | null>;
  imageUrl: string;
  mods: string;
  name: string;
  shaders: string | null;
  version: string;
}

export interface NewsViews {
  id: Generated<number | null>;
  initiator: string;
  news_id: number;
}

export interface RulesContent {
  description: string | null;
  id: Generated<number | null>;
  punishment: string | null;
  rule_list_id: string;
  subtitle: string | null;
  title: string;
}

export interface RulesTermins {
  article_desc: string;
  article_title: string;
  id: Generated<number | null>;
}

export interface DB {
  ip_list: IpList;
  minecraft_news: MinecraftNews;
  modpacks: Modpacks;
  news_views: NewsViews;
  rules_content: RulesContent;
  rules_termins: RulesTermins;
}
